name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Subir archivos a Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

      - name: Desplegar en Pages
        uses: actions/deploy-pages@v2
